#FROM node:20-alpine
FROM node:20-alpine

RUN apk update && apk add --no-cache \
      sudo \
      curl \
      build-base \
      g++ \
      libpng \
      libpng-dev \
      jpeg-dev \
      pango-dev \
      cairo-dev \
      giflib-dev \
      python3 \
      ;

COPY package.json .

RUN npm install -g npm@latest
RUN npm install husky
RUN npm install

RUN npm install sharp
COPY --chown=node:node . ./

USER node
EXPOSE 3000
CMD ["npm", "run", "start"]