name: site-tld-strapi-full-local
services:
  postgres-local:
    extends:
      file: ./local/postgres/docker-compose.yaml
      service: postgres-local
  strapi-local:
    extends:
      file: ./site-tld/docker-compose.yaml
      service: strapi-local
    depends_on:
      postgres-local:
        condition: service_healthy