name: mqtt-grpc-local

services:
  grpc-local:
    container_name: grpc-local
    build:
      context: ./grpc/site-tld/
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
    command: 
      - /meshtk/meshtk
      - server
      - proxy
      - --verbose=trace

  mqtt-local:
    container_name: mqtt-local
    build:
      context: ./mosquitto/site-tld/
      dockerfile: Dockerfile
    ports:
      - "1884:1884"