name: mqtt-grpc-local

services:
  grpc-local:
    container_name: grpc-local
    build:
      context: ./grpc/site-tld/
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
    environment:
      - MESHTK_SERVER_PROXYFORWARDADDRESS=mqtt-local:1884
    depends_on:
      mqtt-local:
        condition: service_healthy

    volumes:
      - ./grpc/site-tld/logs:/meshtk/logs

    command: 
      - /meshtk/meshtk
      - server
      - proxy
      - --verbose=trace

  mqtt-local:
    container_name: mqtt-local
    build:
      context: ./mosquitto/site-tld/
      dockerfile: Dockerfile
    ports:
      - "1884:1884"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1884"]
      interval: 1s
      timeout: 1s
      retries: 3