name: mqtt-grpc-local

services:
  grpc-local:
    container_name: grpc-local
    build:
      context: ./grpc/site-tld/
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
    environment:
      - MESHTK_SERVER_PROXYFORWARDADDRESS=mqtt-local:1884
      - MESHTK_BLOCK_S3_REGION=us-east-1
      - MESHTK_BLOCK_S3_NAME=meshtk-blocklist-20250514
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

    depends_on:
      mqtt-local:
        condition: service_healthy

    volumes:
      - ./grpc/site-tld/logs:/meshtk/logs

    command: 
      - /meshtk/meshtk
      - server
      - proxy
      - --verbose=trace

  mqtt-local:
    container_name: mqtt-local
    build:
      context: ./mosquitto/site-tld/
      dockerfile: Dockerfile
    ports:
      - "1884:1884"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1884"]
      interval: 1s
      timeout: 1s
      retries: 3